title: "Sistema Solar"
description: "Explorando el Sistema Solar"
theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"

nav:
  - title: "Planetas"
    url: "/planetas/"
    children:
      - title: "Planetas Interiores"
        url: "/planetas/interiores/"
      - title: "Planetas Exteriores"
        url: "/planetas/exteriores/"
  - title: "Lunas"
    url: "/lunas/"
  - title: "Sol"
    url: "/sol/"
    
nav_external_links:
  - title: "Just the Docs on GitHub"
    url: "https://www.nasa.gov"
    hide_icon: false 
    opens_in_new_tab: true 


search_enabled: false
