title: "Sistema Solar"
description: "Explorando el Sistema Solar"
theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"

nav:
  - title: "Planetas"
    url: "planetas"
    children:
      - title: "Planetas Interiores"
        url: "/planetas/interiores/"
      - title: "Planetas Exteriores"
        url: "/planetas/exteriores/"
  - title: "Lunas"
    url: "lunas"
  - title: "Sol"
    url: "sol"
  - title: "NASA"
    url: "https://www.nasa.gov"
    external: true

search_enabled: false
