title: "Sistema Solar"
logo: "/assets/images/sol.png"
theme: just-the-docs

just_the_docs:
  search_enabled: false
  navigation:
    - title: "El Sol"
      url: /sol/
    - title: "Planetas"
      url: /planetas/
      children:
        - title: "Mercurio"
          url: /planetas/mercurio/
        - title: "Venus"
          url: /planetas/venus/
        - title: "Tierra"
          url: /planetas/tierra/
        - title: "Marte"
          url: /planetas/marte/
    - title: "Otros Cuerpos Celestes"
      url: /cuerpos-celestes/
    - title: "NASA (Enlace Externo)"
      url: https://www.nasa.gov/
      external: true
