title: "Sistema Solar"
logo: "https://www.mundodeportivo.com/urbantecno/hero/2023/02/sistema_solar.1676924665.5214.jpg?width=768&aspect_ratio=16:9&format=nowebp"
description: "Explorando el Sistema Solar"
theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"

nav:
  - title: "Planetas"
    url: "/planetas/"
    children:
      - title: "Planetas Interiores"
        url: "/planetas/interiores/"
      - title: "Planetas Exteriores"
        url: "/planetas/exteriores/"
  - title: "Lunas"
    url: "/lunas/"
  - title: "Sol"
    url: "/sol/"
    
nav_external_links:
  - title: Página oficial de la NASA
    url: "https://www.nasa.gov"
    hide_icon: false
    opens_in_new_tab: true


search_enabled: false
